version: '3'

services:
  iorung:
    environment:
      - PORT=8002
      - AUTH_REDIS_URL=redis://auth-redis
      - SOCKET_REDIS_URL=redis://socket-redis
      - MONGODB_URI=mongodb://db:27017/rung
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/go/src/github.com/minhajuddinkhan/iorung/"
    ports:
      - "8002:8002"

  auth-redis:
    image: redis
    expose:
      - 6379

  socket-redis:
    image: redis
    expose:
      - 6379

  db:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=rung
      - MONGO_INITDB_USERNAME=pattaplayer
      - MONGO_INITDB_PASSWORD=secret
    ports:
      - "27017:27017"