version: '3'

services:
  iorung:
    environment:
      - HOST=iorung
      - PORT=8002
      - RPC_PORT=8003
      - AUTH_REDIS_URL=redis://auth-redis
      - SOCKET_REDIS_URL=redis://socket-redis
      - MONGODB_URI=mongodb://db:27017/test_rung
      - JWT_SECRET=goo
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/go/src/github.com/minhajuddinkhan/iorung/"
    ports:
      - "8002:8002"

  iorung_test_suite:
    environment:
      - PORT=8002
      - HOST=iorung
    depends_on:
      - iorung
    build:
      context: .
      dockerfile: Dockerfile-test
    volumes:
      - ".:/go/src/github.com/minhajuddinkhan/iorung/"

  auth-redis:
    image: redis
    expose:
      - 6379

  socket-redis:
    image: redis
    expose:
      - 6379
